name: Run Tests

on:
    push:
        paths:
            - "00.distributed-node/**"
        branches:
            - main
    pull_request:
        paths:
            - "00.distributed-node/**"
        branches:
            - main

jobs:
    test:
        name: Run Tests for recipe-api and web-api
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout Code
              uses: actions/checkout@v3

            # Set up Node.js
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18" # Specify the Node.js version you want to use

            # Cache Node.js dependencies
            - name: Cache Node.js Modules
              uses: actions/cache@v3
              with:
                  path: |
                      00.distributed-node/**/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('00.distributed-node/**/package-lock.json', '00.distributed-node/**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            # Install dependencies and run tests for recipe-api
            - name: Install and Test recipe-api
              working-directory: ./00.distributed-node/recipe-api
              run: |
                  npm ci
                  npm test

            # Install dependencies and run tests for web-api
            - name: Install and Test web-api
              working-directory: ./00.distributed-node/web-api
              run: |
                  npm ci
                  npm test
