services:
    web-api:
        container_name: Consumer
        build: ./web-api
        ports:
            - "3001:3001"
        depends_on:
            - recipe-api
        volumes:
            - ./web-api:/web-api

    recipe-api:
        container_name: Producer
        build: ./recipe-api
        ports:
            - "5000:5000"
        volumes:
            - ./recipe-api:/recipe-api
